### ISSUE TITLE
[BUG] Can't use qr code sign-in unless close

### ISSUE THREAD

**Issue by r2dev2** [lynbrookhs/lynbrook-app#1]
When using the sign-in with qr code for clubs, I cannot sign in unless the qr code occupies the full qr code target. In the iOS app, I think it is solved by zooming in to expand the qr code into the target.

A solution to this could be to either enable zooming with the camera or through using a sliding window to see which part of the image has the qr code.

**Comment by r2dev2** [comment]
I'm working on this btw

**Comment by oliver-ni** [comment]
The QR code scanning is handled by expo-camera. The guides displayed on the screen do not actually mean anything.

It's worked for me without it needing to occupy the full target. Allowing zoom might help though.

**Comment by r2dev2** [comment]
Fixed in #2 and also default camera app works.
