### ISSUE TITLE
Add Travis continuous integration bot for Lynbrook APP

### ISSUE THREAD

**Issue by ConcurrencyPractitioner** [lynbrookhs/lynbrook-app#27]
It is practically standard convention in most production code apps to commit PRs in a continuous integration environment (abbreviated as CI). It is therefore excellent practice to also have a bot which tests if the code you added breaks compatibility / causes other issues.  In the future, if we want to standardize code, we can include checkstyle as well as spotbugs to our bot. For now, we can just add a basic Travis CI bot that tests for merge compatibility.

**Comment by oliver-ni** [comment]
We have CI. Click actions tab.
