### ISSUE TITLE
Home Page Edits

### ISSUE THREAD

**Issue by mzhao80** [lynbrookhs/lynbrook-app#34]
-change the title at the top from "Lynbrook Spirit" to "Lynbrook High School"

-Between the Person/Email box and the points box, add a new box that says that there are [current-period-end-time - current-time] minutes until [current-period] ends at []

**Comment by oliver-ni** [comment]
Closed by f43e794d0706502f922370225822d302d330da56

**Comment by mzhao80** [comment]
Display the time school starts tomorrow after the final period each day. School starting time is in part determined by an initialization questions asking them to check what periods they have school.
