### ISSUE TITLE
guest accounts

### ISSUE THREAD

**Issue by mzhao80** [lynbrookhs/lynbrook-app#37]
Must be able to create new users. Should probably allow for standard user/pass login too as an alternative.

**Comment by oliver-ni** [comment]
Creating new users is already a thing, though

**Comment by oliver-ni** [comment]
I thought we restricted to signing in with Google to make sure people don't make multiple accounts, can you clarify?

**Comment by mzhao80** [comment]
I tried creating a new user yesterday and it didn't seem to work. 

Are we able to restrict Google sign-ins to just FUHSD accounts? If not, there's not too much benefit. If we are, then we should still allow user/pass sign-ins for members of the community and maybe just restrict what they can see (no class news)

**Comment by oliver-ni** [comment]
Google sign-ins are already restricted to FUHSD

**Comment by mzhao80** [comment]
Ok, sounds good. We should still provide another sign-in options for members of the community such as parents but with limited features.

**Comment by oliver-ni** [comment]
got it

**Comment by oliver-ni** [comment]
See #44

**Comment by mzhao80** [comment]
- Guests should be able to filter which clubs they want to look at
- This filter should persist through opening/closing the app
- Guests should be able to see time to next period
