### ISSUE TITLE
Construct an all-encompassing admin interface for Lynbrook App

### ISSUE THREAD

**Issue by ConcurrencyPractitioner** [lynbrookhs/lynbrook-app#49]
After some thinking, I've realized a core few steps which absolutely should be taken into account:

Currently, for announcements to be made, one will have to manually insert them into a database. For non tech-savvy people, it is a huge burden for them to learn Linux commands or the like. Also, for event postings, and other stuff, we have to do something similar.

This is all about usability. Therefore, I propose that we also build a website for the app powered by Github Pages, while connected to Oliver's database (Firebase). In effect, all announcements can be added through this website. At a high level standpoint, the website is a platform from which clubs and other admins can control the database without having to learn _complicated bash commands_.  

This is I believe absolutely mandatory for this app, and something that the Monta Vista app lacks. We wish to require usability above all else, and this would be an important step towards accomplishing that.

**Comment by ConcurrencyPractitioner** [comment]
@mzhao80 @oliver-ni  I think this is pretty important, and should be prioritized. We need to be alleviate the burden for the user, and avoid as much as possible having _them_  to go through the hassle of doing all these manual database insertions.

**Comment by ConcurrencyPractitioner** [comment]
We probably can extends this to creating surveys on here, as well as include some features for users and the Lynbrook student community in general. (Not necessarily restrict this to administratros)

**Comment by ConcurrencyPractitioner** [comment]
Note: This is already partially complete with this repository:
https://github.com/lynbrookhs/lynbrook-app-admin

We just need to enable creation of surveys and other features.

**Comment by oliver-ni** [comment]
please ask about the project status before making issues like this
